# Generated by Django 3.0.3 on 2020-02-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('competition_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCompetitionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Create time')),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of the last change.')),
                ('name', models.CharField(help_text='Name of the event', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the run', null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_calendar.CompetitionModel')),
                ('create_by', models.ForeignKey(blank=True, editable=False, help_text='User how create this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamcompetitionevent_create_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, editable=False, help_text='User as last edit this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamcompetitionevent_last_update_by', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Create time')),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of the last change.')),
                ('name', models.CharField(help_text='Name of the event', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the run', null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('start_date', models.DateField(help_text='Start date of the Workout', verbose_name='start date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('ascent', models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Ascent')),
                ('descent', models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Descent')),
                ('peace', models.SmallIntegerField(blank=True, help_text='average pace at which you plan to run.', null=True, verbose_name='planned peace')),
                ('gpx', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('create_by', models.ForeignKey(blank=True, editable=False, help_text='User how create this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userworkoutevent_create_by', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(blank=True, editable=False, help_text='User as last edit this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userworkoutevent_last_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamWorkoutEvent',
            fields=[
                ('userworkoutevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.UserWorkoutEvent')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.userworkoutevent',),
        ),
        migrations.CreateModel(
            name='UserWorkoutParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.UserWorkoutEvent')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWorkoutParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.TeamWorkoutEvent')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEventParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_calendar.DistanceModel')),
                ('team_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.TeamCompetitionEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'distance')},
            },
        ),
    ]
