# Generated by Django 3.0.3 on 2020-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamworkoutevent',
            name='ascent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ascent'),
        ),
        migrations.AlterField(
            model_name='teamworkoutevent',
            name='descent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Descent'),
        ),
        migrations.AlterField(
            model_name='userworkoutevent',
            name='ascent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ascent'),
        ),
        migrations.AlterField(
            model_name='userworkoutevent',
            name='descent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Descent'),
        ),
    ]
