# Generated by Django 3.0.3 on 2020-02-18 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=4, help_text='The ideal track length in kilometer.', max_digits=7, unique=True)),
            ],
            options={
                'verbose_name': 'Distance',
                'verbose_name_plural': 'Distances',
                'ordering': ('-distance_km',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(blank=True, help_text='Sequential number of the event', null=True)),
                ('name', models.CharField(help_text='Name of the event', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the run', null=True)),
                ('description', models.TextField(blank=True, help_text='Description date of the run', null=True)),
                ('distances', models.ManyToManyField(to='competition_calendar.DistanceModel')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-start_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CompetitionLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Create time')),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of the last change.')),
                ('url', models.URLField(help_text='Link URL')),
                ('text', models.CharField(blank=True, help_text='Link text (leave empty to generate it from url)', max_length=127, null=True)),
                ('title', models.CharField(blank=True, help_text='Link title (leave empty to generate it from url)', max_length=127, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='competition_calendar.CompetitionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
