# Generated by Django 3.0.3 on 2020-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='ITRA_points',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ITRA points'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='ascent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ascent'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='descent',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Descent'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='mountain_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mountain level'),
        ),
    ]
