# Generated by Django 3.0.3 on 2020-04-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance_km',
            field=models.DecimalField(decimal_places=4, help_text='The ideal track length in kilometer.', max_digits=7, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the distance', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('distance_km', 'competition')},
        ),
    ]
