# Generated by Django 3.0.3 on 2020-02-18 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionmodel',
            options={'ordering': ('-start_date', '-pk'), 'verbose_name': 'Competition', 'verbose_name_plural': 'Competition'},
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Create time'),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of the last change.'),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='text',
            field=models.CharField(blank=True, help_text='Link text (leave empty to generate it from url)', max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='title',
            field=models.CharField(blank=True, help_text='Link title (leave empty to generate it from url)', max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, help_text='Link URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompetitionLinkModel',
        ),
    ]
