# Generated by Django 3.0.3 on 2020-02-25 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the Event', null=True),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the Event'),
            preserve_default=False,
        ),
    ]
