# Generated by Django 3.0.3 on 2020-02-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_calendar', '0002_auto_20200218_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionmodel',
            name='distances',
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='ITRA_points',
            field=models.SmallIntegerField(blank=True, max_length=1, null=True, verbose_name='ITRA points'),
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='ascent',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Ascent'),
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition_calendar.CompetitionModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='descent',
            field=models.SmallIntegerField(blank=True, max_length=5, null=True, verbose_name='Descent'),
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='mountain_level',
            field=models.SmallIntegerField(blank=True, max_length=1, null=True, verbose_name='Mountain level'),
        ),
        migrations.AddField(
            model_name='distancemodel',
            name='name',
            field=models.CharField(default=1, help_text='Name of the distance', max_length=255),
            preserve_default=False,
        ),
    ]
